// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class RegistraClienteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registraCliente() {
    driver.get("http://localhost:8080/nyahfoodXP/index.jsp");
    driver.manage().window().setSize(new Dimension(1063, 799));
    driver.findElement(By.linkText("Registrar Cliente")).click();
    driver.findElement(By.name("txtNomeCliente")).click();
    driver.findElement(By.name("txtNomeCliente")).sendKeys("Braian Anderson de Souza Alves");
    driver.findElement(By.name("txtEmailCliente")).sendKeys("braian.eletrica@gmail.com");
    driver.findElement(By.name("txtTelefoneCliente")).sendKeys("35991434352");
    driver.findElement(By.id("cep")).sendKeys("37 440 000");
    driver.findElement(By.id("cidade")).sendKeys("Caxambu");
    driver.findElement(By.id("uf")).sendKeys("Minas Gerais");
    driver.findElement(By.name("txtCpfCliente")).click();
    driver.findElement(By.name("txtCpfCliente")).sendKeys("12376668646");
    driver.findElement(By.name("txtSenhaCliente")).click();
    driver.findElement(By.name("txtSenhaCliente")).sendKeys("123123123");
    driver.findElement(By.id("rua")).click();
    driver.findElement(By.id("rua")).sendKeys("Rua Bernardo Mascarenhas");
    driver.findElement(By.id("bairro")).click();
    driver.findElement(By.id("bairro")).sendKeys("Fábrica");
    driver.findElement(By.name("txtNumeroCliente")).click();
    driver.findElement(By.name("txtNumeroCliente")).sendKeys("992");
    driver.findElement(By.name("txtComplementoCliente")).click();
    driver.findElement(By.name("txtComplementoCliente")).sendKeys("asdas");
    driver.findElement(By.name("btnConfirmar")).click();
    driver.close();
  }
}
